# Same real physical signal in the two supported conventions. Never replace the
# frozen negative-time reference data with values generated by the new solver.
@testset "native phasor conjugation" begin
    T = Float32
    mesh = BoundaryMesh(SVector{3,T}[
        (0,0,0), (1,0,0), (0,1,0), (0,0,1)],
        [(1,3,2), (1,2,4), (1,4,3), (2,3,4)], ones(Int,4))
    p1, dp0 = build_p1_space(mesh), build_dp0_space(mesh)
    rule = triangle_rule(T, 3)
    k = T(0.7)
    ipp = assemble_l2_identity_matrix(mesh,p1,dp0,rule,:p1,:p1)
    ipq = assemble_l2_identity_matrix(mesh,p1,dp0,rule,:p1,:dp0)
    qminus = ComplexF32[1+2im, .3-.2im, -.1+.4im, .7+.2im]
    points = [SVector{3,T}(2,2,2), SVector{3,T}(-2,1,3)]
    cache = build_field_evaluation_cache(mesh,rule)
    results = map((NEGATIVE_TIME_PHASOR, POSITIVE_TIME_PHASOR)) do convention
        with_phasor_convention(convention) do
            q = convention == NEGATIVE_TIME_PHASOR ? qminus : conj.(qminus)
            op = assemble_regular_galerkin_operators(mesh,p1,dp0,k,rule;
                skip_singular=false,singular_order=3,backend=:cpu)
            a,b = BeatEngineCore.burton_miller_neumann_matrices(op,ipp,ipq,k)
            p = solve_burton_miller_neumann(op,ipp,ipq,q,k)
            field = evaluate_galerkin_field_cpu(points,mesh,p,q,k,cache)
            if cuda_available()
                dc = build_cuda_regular_assembly_cache(mesh,rule)
                sc = build_singular_correction_cache(mesh,3)
                dsc = BeatEngineCore.build_cuda_singular_correction_cache(sc,p1,dp0)
                gpu = assemble_regular_galerkin_operators(mesh,p1,dp0,k,rule;
                    skip_singular=false,singular_order=3,backend=:cuda,
                    device_cache=dc,singular_cache=sc,device_singular_cache=dsc)
                for key in (:single_layer,:double_layer,:adjoint_double_layer,:hypersingular)
                    @test Array(getproperty(gpu,key)) ≈ getproperty(op,key) rtol=3f-3 atol=3f-4
                end
                dq = CUDA_MODULE.CuArray(q)
                direct = assemble_burton_miller_neumann_system_cuda(mesh,p1,dp0,dq,k,rule;
                    device_cache=dc,singular_cache=sc,device_singular_cache=dsc)
                @test Array(direct.matrix) ≈ a rtol=3f-3 atol=3f-4
                @test Array(direct.rhs) ≈ b*q rtol=3f-3 atol=3f-4
                rhs = assemble_burton_miller_rhs_cuda(mesh,p1,dp0,dq,k,rule;
                    device_cache=dc,singular_cache=sc,device_singular_cache=dsc)
                @test Array(rhs) ≈ b*q rtol=3f-3 atol=3f-4
                @test solve_burton_miller_system_cuda!(direct) ≈ p rtol=5f-3 atol=3f-4
                gc = build_cuda_field_evaluation_cache(cache)
                @test evaluate_galerkin_field_cuda(points,mesh,p,q,k,gc) ≈ field rtol=5f-4 atol=5f-5
                release_burton_miller_system_cuda!(direct)
                release_operator_storage!(gpu)
                CUDA_MODULE.unsafe_free!(dq)
                CUDA_MODULE.unsafe_free!(rhs)
            end
            if metal_available()
                dc = build_metal_regular_assembly_cache(mesh,p1,dp0,rule; singular_order=3)
                sc = build_singular_correction_cache(mesh,3)
                dsc = build_metal_singular_correction_cache(sc)
                gpu = assemble_regular_galerkin_operators(mesh,p1,dp0,k,rule;
                    skip_singular=false,singular_order=3,backend=:metal,
                    device_cache=dc,singular_cache=sc,device_singular_cache=dsc)
                host = metal_host_operators(gpu)
                for key in (:single_layer,:double_layer,:adjoint_double_layer,:hypersingular)
                    @test getproperty(host,key) ≈ getproperty(op,key) rtol=3f-3 atol=3f-4
                end
                direct = assemble_burton_miller_neumann_system_metal(mesh,p1,dp0,q,k,rule;
                    device_cache=dc,singular_cache=sc,device_singular_cache=dsc,
                    identity_p1_p1=ipp,identity_p1_dp0=ipq,singular_order=3)
                METAL_MODULE.synchronize()
                @test Array(direct.matrix) ≈ a rtol=3f-3 atol=3f-4
                @test vec(Array(direct.rhs)) ≈ b*q rtol=3f-3 atol=3f-4
                @test vec(solve_metal_burton_miller_system(direct)) ≈ p rtol=5f-3 atol=3f-4
                gc = build_metal_field_evaluation_cache(cache)
                @test evaluate_galerkin_field_metal(points,mesh,p,q,k,gc) ≈ field rtol=5f-4 atol=5f-5
                release_metal_field_evaluation_cache!(gc)
                release_metal_burton_miller_system!(direct)
                release_operator_storage!(host)
                release_metal_singular_correction_cache!(dsc)
                release_metal_regular_assembly_cache!(dc)
            end
            (;a,b,p,field)
        end
    end
    for key in (:a,:b,:p,:field)
        @test getproperty(results[2],key) ≈ conj.(getproperty(results[1],key)) rtol=1f-5 atol=1f-6
    end
    @test phasor_convention() == NEGATIVE_TIME_PHASOR
    @test_throws ErrorException with_phasor_convention(() -> error("test"), POSITIVE_TIME_PHASOR)
    @test phasor_convention() == NEGATIVE_TIME_PHASOR
    with_phasor_convention(POSITIVE_TIME_PHASOR) do
        @test time_derivative(2.0) == 2im
        @test neumann_scale(1.2,2.0) == -2.4im
        @test burton_miller_coupling(2.0) == -.5im
        @test outgoing_wavenumber(2.0) == -2.0
        @test outgoing_wavenumber(outgoing_wavenumber(2.0)) == -2.0
    end
end

@testset "damped FEM and passive models conjugate" begin
    mesh = load_gmsh41_volume(joinpath(COUPLED_FIXTURE_ROOT,"femvolume.msh"),0.001)
    stiffness,mass = assemble_p1_fem_matrices(mesh)
    transducer = ElectrodynamicTransducer{Float64}("t",Int[],Float64[],Int[],Float64[],
        SVector(0.,0.,1.),1.,1,6.,.0005,7.,.015,.0005,1.,
        SemiInductanceModel{Float64}(6.2,.0001,.001,.04,1000.),
        LumpedSealedRearChamber{Float64}(.001,.01))
    for frequency in (50.,100.,500.)
        values = map((NEGATIVE_TIME_PHASOR, POSITIVE_TIME_PHASOR)) do convention
            with_phasor_convention(convention) do
                w = 2pi*frequency
                (assemble_fem_dynamic_stiffness(stiffness,mass,w/343.;bulk_loss_factor=.001),
                 miki_rigid_backed_surface_admittance(frequency,343.,1.21,.03,5000.),
                 electrical_impedance(transducer,w), mechanical_impedance(transducer,w,1.21,343.))
            end
        end
        for (minus,plus) in zip(values...)
            @test plus ≈ conj.(minus) rtol=1e-12
        end
        @test real(values[2][2]) > 0
        @test imag(values[2][3]) > 0
    end
end

if get(ENV,"BLAB_RUN_COUPLED_REFERENCE","0") == "1"
    @testset "coupled complex excitations conjugate near cavity pole" begin
        fem = load_gmsh41_volume(joinpath(COUPLED_FIXTURE_ROOT,"femvolume.msh"),0.001)
        bem = load_gmsh22_with_tags(joinpath(COUPLED_FIXTURE_ROOT,"exterior_conforming.msh"),0.001)
        mapping = build_conforming_interface_map(fem,bem,physical_tag(fem,2,"Interface"),2)
        tag = physical_tag(fem,2,"Radiator")
        stiffness,mass = assemble_p1_fem_matrices(fem)
        interior = setdiff(1:length(fem.vertices),unique(mapping.fem_vertex_indices))
        eigenvalues = eigen(Symmetric(Matrix(stiffness[interior,interior])),
            Symmetric(Matrix(mass[interior,interior]))).values
        pole = 343.0*sqrt(first(filter(x -> x > 1e-8*maximum(abs,eigenvalues),sort(eigenvalues))))/(2pi)
        transducer = ElectrodynamicTransducer{Float64}("t",[tag],[1.0],[1],[-1.0],
            SVector(0.,0.,1.),2.,1,6.,.0005,7.,.015,.0005,1.)
        for frequency in (pole*.999,pole*1.001)
            for condensed in (false,true)
                solutions = map((NEGATIVE_TIME_PHASOR,POSITIVE_TIME_PHASOR)) do convention
                    with_phasor_convention(convention) do
                        build = condensed ? build_condensed_coupled_system : build_coupled_system
                        system = build(fem,bem,mapping,frequency,343.,1.21;
                            quadrature_order=1,singular_order=1,bulk_loss_factor=1e-4,
                            transducers=[transducer])
                        amplitude = convention == NEGATIVE_TIME_PHASOR ? 0.3+0.7im : 0.3-0.7im
                        excitation = (kind=:voltage,radiator_tag=0,transducer_index=1,amplitude=amplitude)
                        try
                            solve = condensed ? solve_condensed_coupled_excitations : solve_coupled_excitations
                            only(solve(system,[excitation]))
                        finally
                            if condensed
                                release_condensed_coupled_system!(system)
                            else
                                release_coupled_system!(system)
                            end
                        end
                    end
                end
                for key in (:fem_pressure,:bem_pressure,:interface_flux,:bem_neumann,:diaphragm_velocity,:voice_coil_current)
                    @test isapprox(getproperty(solutions[2],key),conj.(getproperty(solutions[1],key));rtol=1e-8,atol=1e-10)
                end
            end
        end
    end
end
